// This file is auto-generated by tauri-specta. DO NOT EDIT.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	// Ping command — proves direct IPC round-trip works.
	ping: () => typedError<PingResponse, RustacleError>(__TAURI_INVOKE("ping")),
	// Version command — returns the app version from Cargo.toml.
	version: () => __TAURI_INVOKE<string>("version"),
	// List all loaded plugins.
	listPlugins: () => typedError<ListPluginsResponse, RustacleError>(__TAURI_INVOKE("list_plugins")),
	/**
	 *  Call a plugin command through the kernel registry.
	 *  This is the core integration proof: UI → IPC → Kernel → Plugin → back.
	 */
	pluginCall: (request: PluginCallRequest) => typedError<PluginCallResponse, RustacleError>(__TAURI_INVOKE("plugin_call", { request })),
	/**
	 *  Send a prompt to the agent, starting a new turn.
	 * 
	 *  Spawns the harness loop in the background and streams reasoning steps
	 *  as Tauri events. Returns the turn ID immediately.
	 */
	sendPrompt: (request: SendPromptRequest) => typedError<SendPromptResponse, RustacleError>(__TAURI_INVOKE("send_prompt", { request })),
	// Stop an active agent turn.
	stopTurn: (request: StopTurnRequest) => typedError<StopTurnResponse, RustacleError>(__TAURI_INVOKE("stop_turn", { request })),
	// List available model profiles from settings store.
	listModelProfiles: () => typedError<ListModelProfilesResponse, RustacleError>(__TAURI_INVOKE("list_model_profiles")),
	// Respond to a permission request from the agent.
	respondPermission: (request: RespondPermissionRequest) => typedError<null, RustacleError>(__TAURI_INVOKE("respond_permission", { request })),
	// Get a setting value by key.
	getSetting: (request: GetSettingRequest) => typedError<GetSettingResponse, RustacleError>(__TAURI_INVOKE("get_setting", { request })),
	// Set a setting value by key. Emits `settings:changed` event on success.
	setSetting: (request: SetSettingRequest) => typedError<null, RustacleError>(__TAURI_INVOKE("set_setting", { request })),
	// Test a model connection by sending a minimal chat completion request.
	testModelConnection: (request: TestModelRequest) => typedError<TestModelResponse, RustacleError>(__TAURI_INVOKE("test_model_connection", { request })),
};

/* Types */
// Agent interaction mode.
export type AgentMode = 
// Full tools enabled, `ReAct` loop.
"Chat" | 
// Read-only tools only, planning overlay.
"Plan" | 
// No tools, direct Q&A.
"Ask";

// Request for `get_setting`.
export type GetSettingRequest = {
	key: string,
};

// Response from `get_setting`. Value is a JSON string.
export type GetSettingResponse = {
	key: string,
	// JSON-encoded value string.
	value_json: string,
};

// Response from `list_model_profiles`.
export type ListModelProfilesResponse = {
	profiles: ProfileSummary[],
};

// Response from `list_plugins`.
export type ListPluginsResponse = {
	plugins: PluginSummary[],
};

// Permission decision from the user.
export type PermissionDecision = "Deny" | "AllowOnce" | "AllowAlways";

// Response from the `ping` command.
export type PingResponse = {
	message: string,
	timestamp: number,
};

// Request to call a plugin command.
export type PluginCallRequest = {
	plugin_id: string,
	command: string,
	payload: string,
};

// Response from a plugin command call.
export type PluginCallResponse = {
	plugin_id: string,
	data: string,
};

// Plugin lifecycle state.
export type PluginState = "Loading" | "Running" | "Suspended" | "Error";

// Summary of a loaded plugin.
export type PluginSummary = {
	id: string,
	version: string,
	state: PluginState,
};

// Summary of a model profile for the quick-switcher.
export type ProfileSummary = {
	name: string,
	provider: string,
	model: string,
};

// Input for `respond_permission`.
export type RespondPermissionRequest = {
	turn_id: string,
	step_id: string,
	decision: PermissionDecision,
};

/**
 *  Typed error enum for all IPC commands.
 *  Serialized as externally tagged JSON for exhaustive TS matching.
 */
export type RustacleError = { kind: "NotFound"; data: {
	resource: string,
} } | { kind: "Denied"; data: {
	action: string,
	reason: string,
} } | { kind: "InvalidInput"; data: {
	field: string,
	message: string,
} } | { kind: "Internal"; data: {
	message: string,
} } | { kind: "PluginError"; data: {
	plugin_id: string,
	message: string,
} };

// Input for `send_prompt`.
export type SendPromptRequest = {
	message: string,
	model_profile: string | null,
	mode: AgentMode,
};

// Response from `send_prompt`.
export type SendPromptResponse = {
	turn_id: string,
};

// Request for `set_setting`. Value is a JSON string.
export type SetSettingRequest = {
	key: string,
	// JSON-encoded value string.
	value_json: string,
};

// Input for `stop_turn`.
export type StopTurnRequest = {
	turn_id: string,
};

// Response from `stop_turn`.
export type StopTurnResponse = {
	cancelled: boolean,
};

// Request for `test_model_connection`.
export type TestModelRequest = {
	provider: string,
	model: string,
	api_base: string,
	api_key: string,
};

// Response from `test_model_connection`.
export type TestModelResponse = {
	ok: boolean,
	message: string,
	latency_ms: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

