// This file is auto-generated by tauri-specta. DO NOT EDIT.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	// Ping command — proves IPC round-trip works.
	ping: () => typedError<PingResponse, RustacleError>(__TAURI_INVOKE("ping")),
	// Version command — returns the app version from Cargo.toml.
	version: () => __TAURI_INVOKE<string>("version"),
};

/* Types */
// Response from the `ping` command.
export type PingResponse = {
	message: string,
	timestamp: number,
};

/**
 *  Typed error enum for all IPC commands.
 *  Serialized as externally tagged JSON for exhaustive TS matching.
 */
export type RustacleError = { kind: "NotFound"; data: {
	resource: string,
} } | { kind: "Denied"; data: {
	action: string,
	reason: string,
} } | { kind: "InvalidInput"; data: {
	field: string,
	message: string,
} } | { kind: "Internal"; data: {
	message: string,
} } | { kind: "PluginError"; data: {
	plugin_id: string,
	message: string,
} };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

